#SHELL := /bin/bash


school:
	@echo "school" #>> ${RES}
#Start of Engineering
MPC: school
	@echo "MPC" #>> ${RES}

JEE: MPC
	@echo "JEE" #>> ${RES}
IIT: JEE
	@echo "IIT" #>> ${RES}
NIT: JEE
	@echo "NIT" #>> ${RES}
Hard.Eng: NIT
	@echo "Hard.Eng" #>> ${RES}
Soft.Eng: IIT
	@echo "Soft.Eng" #>> ${RES}
MS: IIT
	@echo "MS" #>> ${RES}
Research.Eng: Soft.Eng MS
	@echo "Research.Eng" #>> ${RES}
#End of engineering

#Start of Medical
BiPC: school
	@echo "BiPC" #>> ${RES}
NEET: BiPC
	@echo "NEET" #>> ${RES}
AIIMS: NEET
	@echo "AIIMS" #>> ${RES}
ENT: AIIMS
	@echo "ENT" #>> ${RES}
Gynic: AIIMS
	@echo "Gynic" #>> ${RES}
MD: AIIMS
	@echo "MD" #>> ${RES}
IVF.spec: Gynic MD
	@echo "IVF.spec" #>> ${RES}
CMC: NEET
	@echo "CMC" #>> ${RES}
Dentist: CMC
	@echo "Dentist" #>> ${RES}
#end of medical


